name: commercio
description: An e-commerce app
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  slang_flutter: ^3.17.0
  slang: ^3.17.0
  shared_preferences: ^2.1.0
  freezed: ^2.3.3
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  pocketbase: ^0.9.1
  go_router: ^7.0.0
  flutter_screenutil: ^5.7.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  flutter_form_builder: ^9.0.0
  uuid: ^3.0.7
  intl: ^0.18.0
  google_sign_in: ^5.4.4
  stack_trace: ^1.11.0
  firebase_service: ^0.0.1+1
  flutter_dotenv: ^5.0.2
  firebase_storage: ^11.2.0
  form_builder_validators: ^9.0.0
  cloud_functions: ^4.3.0
  firebase_core: ^2.12.0
  firebase_ui_auth: ^1.4.0
  firebase_ui_oauth: ^1.4.0
  firebase_ui_oauth_google: ^1.0.21
  firebase_ui_database: ^1.3.0
  firebase_ui_localizations: ^1.5.0
  cached_network_image: ^3.2.3
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  slang_build_runner: ^3.17.0
  go_router_builder: ^2.0.1
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true

fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf