name: commercio
description: An e-commerce app
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  slang_flutter: ^3.17.0
  slang: ^3.17.0
  shared_preferences: ^2.1.0
  freezed: ^2.3.3
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  pocketbase: ^0.9.1
  go_router: ^7.0.0
  flutter_screenutil: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  slang_build_runner: ^3.17.0

flutter:
  uses-material-design: true
